# Generated by Django 5.1.4 on 2025-01-12 06:00

import User.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', User.user_manager.UserManager()),
            ],
        ),
    ]
